### ISSUE TITLE
Dependencias quebrando o build

### ISSUE THREAD

**Issue by sio-iago** [edubezerra/sca#25]
As dependências novas adicionadas ao pom.xml não estão sendo encontradas pelo maven ao executar "mvn install".

Segue erro:

`[ERROR] Failed to execute goal on project sca: Could not resolve dependencies for project br.cefetrj:sca:war:1.0: The following artifacts could not be resolved: com.db2jcc4:db2jcc4:jar:4.0, br.com.avmb:libsilegacy-crypto:jar:1.0: Could not find artifact com.db2jcc4:db2jcc4:jar:4.0 in central (http://repo.maven.apache.org/maven2) -> [Help 1]`

**Comment by thiamaster** [comment]
Prezado Iago,

Realizei com alguns alunos uma correção para o POM.xml, e respondi como resolver em uma outra issue que criei aqui. 

Para verificar, basta seguir [este link.](https://github.com/edubezerra/sca/issues/30)

Poderia fechar esta issue? Agradeço,
Thiago.
